UnboundLocalError: local variable 'm' referenced before assignment
Summary: error-checking code was expecting at least one line of
error from php.  now it correctly raises detail-less
ProblemStartingPhp() (instead of detail-ful
ProblemStartingPhp(file_name, line_num)) in this rare condition.
no more mysterious 'm' var error message.

Reviewed By: marcel

Test Plan:
- mv /usr/bin/php /usr/bin/php2 and phpsh still gives an error correctly
- normal operation seems fine
- rm -r /etc/phpsh and phpsh start gives better error than before
(tho it's still "phpsh failed to initialize PHP." so maybe we should
check for this better and say something about phpsh being internally
messed up?  idk)

Revert Plan: ok